# DEVELOPMENT
POST http://localhost:8080/api/auth/signup
Content-type: application/json

{
    "username": "Itachi Uchiha",
    "password": "000000"
}

###
POST http://localhost:8080/api/auth/signin
Content-type: application/json

{
    "username": "Itachi Uchiha",
    "password": "000000"
}

###
GET http://localhost:8080/api/mangas
Authorization: Bearer jesuislà

# PRODUCTION