# DEVELOPMENT
POST http://localhost:8080/api/auth/signup
Content-type: application/json

{
    "username": "Obito Hyuga",
    "password": "000000",
    "confirmPass": "000000"
}

###
POST http://localhost:8080/api/auth/signin
Content-type: application/json

{
    "username": "Obito Uchiha",
    "password": "000000"
}

###
GET http://localhost:8080/api/mangas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJJdGFjaGkgVWNoaWhhIiwiaWF0IjoxNjczNzAwMDcxLCJleHAiOjE2NzM4NzI4NzF9.U-bhfUXsEoUcuGSbq9JxYoNH1Scl39GyZjuNDAjAopc

###
GET http://localhost:8080/api/mangas/3/characters
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJJdGFjaGkgVWNoaWhhIiwiaWF0IjoxNjczNzAwMDcxLCJleHAiOjE2NzM4NzI4NzF9.U-bhfUXsEoUcuGSbq9JxYoNH1Scl39GyZjuNDAjAopc

###
GET http://localhost:8080/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJJdGFjaGkgVWNoaWhhIiwiaWF0IjoxNjczNzAwMDcxLCJleHAiOjE2NzM4NzI4NzF9.U-bhfUXsEoUcuGSbq9JxYoNH1Scl39GyZjuNDAjAopc

###
PUT http://localhost:8080/api/users/35
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsInVzZXJuYW1lIjoiT2JpdG8gSHl1Z2EiLCJpYXQiOjE2NzQxMzg3MTksImV4cCI6MTY3NDMxMTUxOX0.fEXcsH1gJijkd42BJAIklxNlo_h2i_Zv3yRw07pVHCI

{
    "username": "Obito Uchiha",
    "password": "000000"
}

###
PUT http://localhost:8080/api/users/1/avatar
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJJdGFjaGkgVWNoaWhhIiwiaWF0IjoxNjczNzAwMDcxLCJleHAiOjE2NzM4NzI4NzF9.U-bhfUXsEoUcuGSbq9JxYoNH1Scl39GyZjuNDAjAopc

{
    "avatar": "/logo.png"
}

###
PUT http://localhost:8080/api/users/35/info
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsInVzZXJuYW1lIjoiT2JpdG8gVWNoaWhhIiwiYXZhdGFyIjoiaHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vZHVteGtkY3ZkL2ltYWdlL3VwbG9hZC92MTY3Mzk3Mjg2MS91d3AyMjAyODA2X211M3ZnaC5qcGciLCJpYXQiOjE2NzQyMjIyMTQsImV4cCI6MTY3NDM5NTAxNH0.dNILvpMJMw76uwAlUV1hieZmmhDAEPh2_Chb4XcpY3w

{
    "username": "Tobi Uchiha"
}

###
POST http://localhost:8080/api/users/8/scores
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJJdGFjaGkgVWNoaWhhIiwiaWF0IjoxNjczNzAwMDcxLCJleHAiOjE2NzM4NzI4NzF9.U-bhfUXsEoUcuGSbq9JxYoNH1Scl39GyZjuNDAjAopc

{
    "manga_id": 1,
    "total": 300
}

###
GET http://localhost:8080/api/mangas/1/scores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJJdGFjaGkgVWNoaWhhIiwiaWF0IjoxNjczNzAwMDcxLCJleHAiOjE2NzM4NzI4NzF9.U-bhfUXsEoUcuGSbq9JxYoNH1Scl39GyZjuNDAjAopc

###
GET http://localhost:8080/api/users/4/mangas/2/scores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJJdGFjaGkgVWNoaWhhIiwiaWF0IjoxNjczNzAwMDcxLCJleHAiOjE2NzM4NzI4NzF9.U-bhfUXsEoUcuGSbq9JxYoNH1Scl39GyZjuNDAjAopc


# PRODUCTION